FROM node:22-alpine AS builder
WORKDIR /app
ARG APP_VERSION=0.1.0
ARG APP_BUILD_ID=0.1.0
ARG GAME_RULES_VERSION=0.1.0
ARG VITE_UMAMI_WEBSITE_ID=
ARG VITE_UMAMI_SCRIPT_URL=
ARG VITE_UMAMI_HOST_URL=
ARG VITE_UMAMI_TELEMETRY_SCRIPT_URL=
ARG VITE_UMAMI_SECONDARY_WEBSITE_ID=
ARG VITE_UMAMI_SECONDARY_HOST_URL=
ARG VITE_SENTRY_DSN=
ARG VITE_SENTRY_TRACES_SAMPLE_RATE=0.1
ENV APP_VERSION=$APP_VERSION
ENV APP_BUILD_ID=$APP_BUILD_ID
ENV GAME_RULES_VERSION=$GAME_RULES_VERSION
ENV VITE_APP_VERSION=$APP_VERSION
ENV VITE_APP_BUILD_ID=$APP_BUILD_ID
ENV VITE_GAME_RULES_VERSION=$GAME_RULES_VERSION
ENV VITE_UMAMI_WEBSITE_ID=$VITE_UMAMI_WEBSITE_ID
ENV VITE_UMAMI_SCRIPT_URL=$VITE_UMAMI_SCRIPT_URL
ENV VITE_UMAMI_HOST_URL=$VITE_UMAMI_HOST_URL
ENV VITE_UMAMI_TELEMETRY_SCRIPT_URL=$VITE_UMAMI_TELEMETRY_SCRIPT_URL
ENV VITE_UMAMI_SECONDARY_WEBSITE_ID=$VITE_UMAMI_SECONDARY_WEBSITE_ID
ENV VITE_UMAMI_SECONDARY_HOST_URL=$VITE_UMAMI_SECONDARY_HOST_URL
ENV VITE_SENTRY_DSN=$VITE_SENTRY_DSN
ENV VITE_SENTRY_TRACES_SAMPLE_RATE=$VITE_SENTRY_TRACES_SAMPLE_RATE
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:22-alpine
WORKDIR /app
ARG APP_VERSION=0.1.0
ARG APP_BUILD_ID=0.1.0
ARG GAME_RULES_VERSION=0.1.0
ARG SENTRY_DSN=
# node:22-alpine 已內建非 root 的 node 使用者
COPY package.json package-lock.json ./
RUN npm ci --omit=dev && npm cache clean --force
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/src ./src
COPY --from=builder /app/data ./data
COPY --from=builder /app/scripts ./scripts
ENV PORT=3000
ENV APP_VERSION=$APP_VERSION
ENV APP_BUILD_ID=$APP_BUILD_ID
ENV GAME_RULES_VERSION=$GAME_RULES_VERSION
ENV SENTRY_DSN=$SENTRY_DSN
EXPOSE 3000
USER node
CMD ["npm", "run", "server"]
