import { createRequire } from 'node:module';
import { describe, expect, it } from 'vitest';

const require = createRequire(import.meta.url);
const { buildSignedImgproxyUrl, isAllowedImgproxyPath, parseAllowedSources, signImgproxyPath } =
  require('../imgproxySigner.cjs') as {
    buildSignedImgproxyUrl: (options: {
      path: string;
      baseUrl: string;
      keyHex: string;
      saltHex: string;
      allowedSources: string[];
    }) => { ok: true; url: string } | { ok: false; status: number; error: string };
    isAllowedImgproxyPath: (path: string, allowedSources: string[]) => boolean;
    parseAllowedSources: (value?: string) => string[];
    signImgproxyPath: (path: string, keyHex: string, saltHex: string) => string;
  };

const keyHex = '0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef';
const saltHex = 'abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789';
const path = '/rs:fit:320:0/plain/https://r2.dan.tw/cards/test/card.jpg@webp';

describe('imgproxy signer', () => {
  it('signs imgproxy paths with the configured key and salt', () => {
    expect(signImgproxyPath(path, keyHex, saltHex)).toBe('F3etKpVaTJSAZuRMKg-o6zEX9l215IAVedQy1v2_0nk');
  });

  it('builds a signed internal imgproxy URL for allowed card image sources', () => {
    const signed = buildSignedImgproxyUrl({
      path,
      baseUrl: 'http://imgproxy:8080/',
      keyHex,
      saltHex,
      allowedSources: ['https://r2.dan.tw/cards/'],
    });

    expect(signed).toEqual({
      ok: true,
      url: `http://imgproxy:8080/F3etKpVaTJSAZuRMKg-o6zEX9l215IAVedQy1v2_0nk${path}`,
    });
  });

  it('rejects unsupported widths and untrusted sources', () => {
    expect(
      isAllowedImgproxyPath('/rs:fit:999:0/plain/https://r2.dan.tw/cards/test/card.jpg', ['https://r2.dan.tw/cards/']),
    ).toBe(false);
    expect(
      isAllowedImgproxyPath('/rs:fit:320:0/plain/https://example.com/cards/test/card.jpg', [
        'https://r2.dan.tw/cards/',
      ]),
    ).toBe(false);
    expect(
      isAllowedImgproxyPath('/rs:fit:320:0/plain/https://r2.dan.tw/profile/avatar.jpg', ['https://r2.dan.tw/cards/']),
    ).toBe(false);
    expect(isAllowedImgproxyPath(`${path}?cacheBust=1`, ['https://r2.dan.tw/cards/'])).toBe(false);
  });

  it('only allows the image variants generated by the frontend', () => {
    expect(
      isAllowedImgproxyPath('/rs:fit:320:0/plain/https://r2.dan.tw/cards/test/card.jpg', ['https://r2.dan.tw/cards/']),
    ).toBe(true);
    expect(path.endsWith('@webp')).toBe(true);
    expect(isAllowedImgproxyPath(path, ['https://r2.dan.tw/cards/'])).toBe(true);
    expect(
      isAllowedImgproxyPath('/rs:fit:320:0/plain/https://r2.dan.tw/cards/test/card.jpg@avif', [
        'https://r2.dan.tw/cards/',
      ]),
    ).toBe(true);
    expect(
      isAllowedImgproxyPath('/rs:fit:320:0/plain/https://r2.dan.tw/cards/test/card%40front.jpg@webp', [
        'https://r2.dan.tw/cards/',
      ]),
    ).toBe(true);
    expect(
      isAllowedImgproxyPath('/rs:fit:320:0/plain/https://r2.dan.tw/cards/test/card.jpg@png', [
        'https://r2.dan.tw/cards/',
      ]),
    ).toBe(false);
    expect(
      isAllowedImgproxyPath('/rs:fit:320:0/plain/https://r2.dan.tw/cards/test/card.jpg@jpg', [
        'https://r2.dan.tw/cards/',
      ]),
    ).toBe(false);
  });

  it('defaults source allowlist to the card image prefix', () => {
    expect(parseAllowedSources()).toEqual(['https://r2.dan.tw/cards/']);
  });
});
