export const RULES_TERMINOLOGY = {
  ja: {
    character: 'キャラクター',
    characterCard: 'キャラクターカード',
    enchant: 'エンチャント',
    enchantCard: 'エンチャントカード',
    areaEnchant: 'エリアエンチャント',
    areaEnchantCard: 'エリアエンチャントカード',
    power: 'パワー',
    powerCost: 'パワーコスト',
    sendToPower: 'SEND TO POWER',
    powerCharger: 'パワーチャージャー',
    abyss: 'アビス',
    battleZone: 'バトルゾーン',
    setZone: 'セットゾーン',
    deckZone: 'デッキゾーン',
    hand: '手札',
    deck: 'デッキ',
    chronos: 'クロノス',
    clock: '時計',
    night: '夜',
    day: '昼',
    dark: '闇',
    flame: '炎',
    electric: '電気',
    wind: '風',
    chaos: 'カオス',
    hp: 'HP',
    attackPower: '攻撃力',
    card: 'カード',
    player: 'プレイヤー',
    opponent: '相手',
    turn: 'ターン',
    battle: 'バトル',
    effect: '効果',
    damage: 'ダメージ',
    damageReduction: 'ダメージ軽減',
    recovery: '回復',
    priorityPlayer: '優先プレイヤー',
    nightSidePlayer: '夜側プレイヤー',
    basicRules: '基本ルール',
    matchSetup: '対戦準備',
    matchFlow: '対戦の流れ',
    cardRulings: 'カード裁定',
    mulligan: '引き直し',
    set: 'セット',
    reveal: '公開',
    timeAdvance: '時間推進',
    characterReplacement: 'キャラクター入れ替え',
    areaEnchantReplacement: 'エリアエンチャント入れ替え',
    effectResolution: '効果処理',
    attackDetermination: '攻撃力決定',
    damageCalculation: 'ダメージ計算',
    turnEnd: 'ターン終了',
    useCard: 'カードを使う',
    activate: '発動',
    nullify: '無効',
    choose: '選ぶ',
    drawCard: 'カードを引く',
    shuffle: 'シャッフル',
    replace: '入れ替える',
    place: '置く',
    returnToDeck: 'デッキに戻す',
    deckTop: 'デッキの一番上',
    deckBottom: 'デッキの底',
    faceUp: '表向き',
    faceDown: '裏向き',
    victory: '勝利',
    defeat: '敗北',
    draw: '引き分け',
  },
  'zh-TW': {
    character: '角色',
    characterCard: '角色卡',
    enchant: '附魔',
    enchantCard: '附魔卡',
    areaEnchant: '區域附魔',
    areaEnchantCard: '區域附魔卡',
    power: 'Power',
    powerCost: 'Power Cost',
    sendToPower: 'SEND TO POWER',
    powerCharger: '充能區',
    abyss: '深淵',
    battleZone: '戰鬥區',
    setZone: '設置區',
    deckZone: '牌組區',
    hand: '手牌',
    deck: '牌組',
    chronos: 'Chronos',
    clock: '時計',
    night: '夜',
    day: '晝',
    dark: '闇',
    flame: '炎',
    electric: '電',
    wind: '風',
    chaos: '混沌',
    hp: 'HP',
    attackPower: '攻擊力',
    card: '卡牌',
    player: '玩家',
    opponent: '對手',
    turn: '回合',
    battle: '戰鬥',
    effect: '效果',
    damage: '傷害',
    damageReduction: '傷害減免',
    recovery: '回復',
    priorityPlayer: '優先玩家',
    nightSidePlayer: '夜側玩家',
    basicRules: '基本規則',
    matchSetup: '對戰準備',
    matchFlow: '對戰流程',
    cardRulings: '卡牌裁定',
    mulligan: '手牌重抽',
    set: '設置',
    reveal: '公開',
    timeAdvance: '時間推進',
    characterReplacement: '角色替換',
    areaEnchantReplacement: '區域附魔替換',
    effectResolution: '效果結算',
    attackDetermination: '攻擊力決定',
    damageCalculation: '傷害計算',
    turnEnd: '回合結束',
    useCard: '使用卡牌',
    activate: '發動',
    nullify: '無效',
    choose: '選擇',
    drawCard: '抽牌',
    shuffle: '洗牌',
    replace: '替換',
    place: '放置',
    returnToDeck: '放回牌組',
    deckTop: '牌組頂',
    deckBottom: '牌組底',
    faceUp: '正面朝上',
    faceDown: '背面朝上',
    victory: '勝利',
    defeat: '敗北',
    draw: '平手',
  },
  'zh-CN': {
    character: '角色',
    characterCard: '角色卡',
    enchant: '附魔',
    enchantCard: '附魔卡',
    areaEnchant: '区域附魔',
    areaEnchantCard: '区域附魔卡',
    power: 'Power',
    powerCost: 'Power Cost',
    sendToPower: 'SEND TO POWER',
    powerCharger: '充能区',
    abyss: '深渊',
    battleZone: '战斗区',
    setZone: '设置区',
    deckZone: '牌组区',
    hand: '手牌',
    deck: '牌组',
    chronos: 'Chronos',
    clock: '时钟',
    night: '夜',
    day: '昼',
    dark: '暗',
    flame: '炎',
    electric: '电',
    wind: '风',
    chaos: '混沌',
    hp: 'HP',
    attackPower: '攻击力',
    card: '卡牌',
    player: '玩家',
    opponent: '对手',
    turn: '回合',
    battle: '战斗',
    effect: '效果',
    damage: '伤害',
    damageReduction: '伤害减免',
    recovery: '恢复',
    priorityPlayer: '优先玩家',
    nightSidePlayer: '夜侧玩家',
    basicRules: '基本规则',
    matchSetup: '对战准备',
    matchFlow: '对战流程',
    cardRulings: '卡牌裁定',
    mulligan: '手牌重抽',
    set: '设置',
    reveal: '公开',
    timeAdvance: '时间推进',
    characterReplacement: '角色替换',
    areaEnchantReplacement: '区域附魔替换',
    effectResolution: '效果结算',
    attackDetermination: '攻击力决定',
    damageCalculation: '伤害计算',
    turnEnd: '回合结束',
    useCard: '使用卡牌',
    activate: '发动',
    nullify: '无效',
    choose: '选择',
    drawCard: '抽牌',
    shuffle: '洗牌',
    replace: '替换',
    place: '放置',
    returnToDeck: '放回牌组',
    deckTop: '牌组顶',
    deckBottom: '牌组底',
    faceUp: '正面朝上',
    faceDown: '背面朝上',
    victory: '胜利',
    defeat: '败北',
    draw: '平手',
  },
  'zh-HK': {
    character: '角色',
    characterCard: '角色卡',
    enchant: '附魔',
    enchantCard: '附魔卡',
    areaEnchant: '區域附魔',
    areaEnchantCard: '區域附魔卡',
    power: 'Power',
    powerCost: 'Power Cost',
    sendToPower: 'SEND TO POWER',
    powerCharger: '充能區',
    abyss: '深淵',
    battleZone: '戰鬥區',
    setZone: '設置區',
    deckZone: '牌組區',
    hand: '手牌',
    deck: '牌組',
    chronos: 'Chronos',
    clock: '時計',
    night: '夜',
    day: '晝',
    dark: '闇',
    flame: '炎',
    electric: '電',
    wind: '風',
    chaos: '混沌',
    hp: 'HP',
    attackPower: '攻擊力',
    card: '卡牌',
    player: '玩家',
    opponent: '對手',
    turn: '回合',
    battle: '戰鬥',
    effect: '效果',
    damage: '傷害',
    damageReduction: '傷害減免',
    recovery: '回復',
    priorityPlayer: '優先玩家',
    nightSidePlayer: '夜側玩家',
    basicRules: '基本規則',
    matchSetup: '對戰準備',
    matchFlow: '對戰流程',
    cardRulings: '卡牌裁定',
    mulligan: '手牌重抽',
    set: '設置',
    reveal: '公開',
    timeAdvance: '時間推進',
    characterReplacement: '角色替換',
    areaEnchantReplacement: '區域附魔替換',
    effectResolution: '效果結算',
    attackDetermination: '攻擊力決定',
    damageCalculation: '傷害計算',
    turnEnd: '回合結束',
    useCard: '使用卡牌',
    activate: '發動',
    nullify: '無效',
    choose: '選擇',
    drawCard: '抽牌',
    shuffle: '洗牌',
    replace: '替換',
    place: '放置',
    returnToDeck: '放回牌組',
    deckTop: '牌組頂',
    deckBottom: '牌組底',
    faceUp: '正面朝上',
    faceDown: '背面朝上',
    victory: '勝利',
    defeat: '敗北',
    draw: '平手',
  },
  en: {
    character: 'Character',
    characterCard: 'Character card',
    enchant: 'Enchant',
    enchantCard: 'Enchant card',
    areaEnchant: 'Area Enchant',
    areaEnchantCard: 'Area Enchant card',
    power: 'Power',
    powerCost: 'Power Cost',
    sendToPower: 'SEND TO POWER',
    powerCharger: 'Power Charger',
    abyss: 'Abyss',
    battleZone: 'Battle Zone',
    setZone: 'Set Zone',
    deckZone: 'Deck Zone',
    hand: 'Hand',
    deck: 'Deck',
    chronos: 'Chronos',
    clock: 'Clock',
    night: 'NIGHT',
    day: 'DAY',
    dark: 'Dark',
    flame: 'Flame',
    electric: 'Electric',
    wind: 'Wind',
    chaos: 'Chaos',
    hp: 'HP',
    attackPower: 'Attack',
    card: 'Card',
    player: 'Player',
    opponent: 'Opponent',
    turn: 'Turn',
    battle: 'Battle',
    effect: 'Effect',
    damage: 'Damage',
    damageReduction: 'Damage reduction',
    recovery: 'Recovery',
    priorityPlayer: 'Priority player',
    nightSidePlayer: 'Night-side player',
    basicRules: 'Basic Rules',
    matchSetup: 'Match Setup',
    matchFlow: 'Match Flow',
    cardRulings: 'Card Rulings',
    mulligan: 'Mulligan',
    set: 'Set',
    reveal: 'Reveal',
    timeAdvance: 'Time advance',
    characterReplacement: 'Character replacement',
    areaEnchantReplacement: 'Area Enchant replacement',
    effectResolution: 'Effect Resolution',
    attackDetermination: 'Attack determination',
    damageCalculation: 'Damage calculation',
    turnEnd: 'Turn end',
    useCard: 'Use a card',
    activate: 'Activate',
    nullify: 'Nullify',
    choose: 'Choose',
    drawCard: 'Draw a card',
    shuffle: 'Shuffle',
    replace: 'Replace',
    place: 'Place',
    returnToDeck: 'Return to the deck',
    deckTop: 'Top of the deck',
    deckBottom: 'Bottom of the deck',
    faceUp: 'Face up',
    faceDown: 'Face down',
    victory: 'Victory',
    defeat: 'Defeat',
    draw: 'Draw',
  },
  ko: {
    character: '캐릭터',
    characterCard: '캐릭터 카드',
    enchant: '인챈트',
    enchantCard: '인챈트 카드',
    areaEnchant: '에리어 인챈트',
    areaEnchantCard: '에리어 인챈트 카드',
    power: 'Power',
    powerCost: 'Power Cost',
    sendToPower: 'SEND TO POWER',
    powerCharger: '파워 차저',
    abyss: '어비스',
    battleZone: '배틀 존',
    setZone: '세트 존',
    deckZone: '덱 존',
    hand: '손패',
    deck: '덱',
    chronos: '크로노스',
    clock: '시계',
    night: '밤',
    day: '낮',
    dark: '어둠',
    flame: '불꽃',
    electric: '전기',
    wind: '바람',
    chaos: '카오스',
    hp: 'HP',
    attackPower: '공격력',
    card: '카드',
    player: '플레이어',
    opponent: '상대',
    turn: '턴',
    battle: '배틀',
    effect: '효과',
    damage: '데미지',
    damageReduction: '데미지 감소',
    recovery: '회복',
    priorityPlayer: '우선 플레이어',
    nightSidePlayer: '밤 쪽 플레이어',
    basicRules: '기본 규칙',
    matchSetup: '대전 준비',
    matchFlow: '대전 흐름',
    cardRulings: '카드 판정',
    mulligan: '멀리건',
    set: '세트',
    reveal: '공개',
    timeAdvance: '시간 진행',
    characterReplacement: '캐릭터 교체',
    areaEnchantReplacement: '에리어 인챈트 교체',
    effectResolution: '효과 처리',
    attackDetermination: '공격력 결정',
    damageCalculation: '데미지 계산',
    turnEnd: '턴 종료',
    useCard: '카드 사용',
    activate: '발동',
    nullify: '무효',
    choose: '선택',
    drawCard: '카드 뽑기',
    shuffle: '셔플',
    replace: '교체',
    place: '놓기',
    returnToDeck: '덱으로 되돌리기',
    deckTop: '덱 맨 위',
    deckBottom: '덱 맨 아래',
    faceUp: '앞면',
    faceDown: '뒷면',
    victory: '승리',
    defeat: '패배',
    draw: '무승부',
  },
} as const;

export type RulesTerminologyLocale = keyof typeof RULES_TERMINOLOGY;

const NON_CANONICAL_PATTERNS: Partial<
  Record<RulesTerminologyLocale, ReadonlyArray<{ pattern: RegExp; expected: string }>>
> = {
  ja: [{ pattern: /\bChronos\b/gu, expected: 'クロノス' }],
  'zh-TW': [
    { pattern: /\bCharacter\b/giu, expected: '角色卡' },
    { pattern: /\bArea Enchant\b/giu, expected: '區域附魔卡' },
    { pattern: /\bEnchant\b/giu, expected: '附魔卡' },
    { pattern: /\bPower Charger\b/giu, expected: '充能區' },
    { pattern: /\bAbyss\b/giu, expected: '深淵' },
    { pattern: /\bBattle Zone\b/giu, expected: '戰鬥區' },
    { pattern: /\bSet Zone\b/giu, expected: '設置區' },
    { pattern: /\bBattle\b/giu, expected: '戰鬥' },
    { pattern: /\b(?:Dark|Flame|Electric|Wind|Chaos)\b/giu, expected: '本地化屬性名' },
    { pattern: /充能成本|PowerCost/gu, expected: 'Power Cost' },
    { pattern: /充能值/gu, expected: 'SEND TO POWER' },
    { pattern: /牌庫/gu, expected: '牌組' },
    { pattern: /暗屬性|火屬性/gu, expected: '闇屬性／炎屬性' },
  ],
  'zh-CN': [
    { pattern: /\bCharacter\b/giu, expected: '角色卡' },
    { pattern: /\bArea Enchant\b/giu, expected: '区域附魔卡' },
    { pattern: /\bEnchant\b/giu, expected: '附魔卡' },
    { pattern: /\bPower Charger\b/giu, expected: '充能区' },
    { pattern: /\bAbyss\b/giu, expected: '深渊' },
    { pattern: /\bBattle Zone\b/giu, expected: '战斗区' },
    { pattern: /\bSet Zone\b/giu, expected: '设置区' },
    { pattern: /\bBattle\b/giu, expected: '战斗' },
    { pattern: /\b(?:Dark|Flame|Electric|Wind|Chaos)\b/giu, expected: '本地化属性名' },
    { pattern: /充能成本|PowerCost/gu, expected: 'Power Cost' },
    { pattern: /充能值/gu, expected: 'SEND TO POWER' },
    { pattern: /牌库/gu, expected: '牌组' },
    { pattern: /闇属性|火属性/gu, expected: '暗属性／炎属性' },
  ],
  'zh-HK': [
    { pattern: /\bCharacter\b/giu, expected: '角色卡' },
    { pattern: /\bArea Enchant\b/giu, expected: '區域附魔卡' },
    { pattern: /\bEnchant\b/giu, expected: '附魔卡' },
    { pattern: /\bPower Charger\b/giu, expected: '充能區' },
    { pattern: /\bAbyss\b/giu, expected: '深淵' },
    { pattern: /\bBattle Zone\b/giu, expected: '戰鬥區' },
    { pattern: /\bSet Zone\b/giu, expected: '設置區' },
    { pattern: /\bBattle\b/giu, expected: '戰鬥' },
    { pattern: /\b(?:Dark|Flame|Electric|Wind|Chaos)\b/giu, expected: '本地化屬性名' },
    { pattern: /充能成本|PowerCost/gu, expected: 'Power Cost' },
    { pattern: /充能值/gu, expected: 'SEND TO POWER' },
    { pattern: /牌庫/gu, expected: '牌組' },
    { pattern: /暗屬性|火屬性/gu, expected: '闇屬性／炎屬性' },
  ],
  en: [
    { pattern: /\bEnergy\b/gu, expected: 'Power Cost' },
    { pattern: /\bCharge\b/gu, expected: 'SEND TO POWER' },
  ],
  ko: [
    { pattern: /\bCharacter\b/gu, expected: '캐릭터 카드' },
    { pattern: /\bArea Enchant\b/gu, expected: '에리어 인챈트 카드' },
    { pattern: /\bEnchant\b/gu, expected: '인챈트 카드' },
    { pattern: /\bPower Charger\b/gu, expected: '파워 차저' },
    { pattern: /\bAbyss\b/gu, expected: '어비스' },
    { pattern: /\bBattle Zone\b/gu, expected: '배틀 존' },
    { pattern: /\bSet Zone\b/gu, expected: '세트 존' },
    { pattern: /\bBattle\b/gu, expected: '배틀' },
    { pattern: /\bClock\b/gu, expected: '시계' },
    { pattern: /파워 코스트|PowerCost/gu, expected: 'Power Cost' },
    { pattern: /충전값/gu, expected: 'SEND TO POWER' },
    { pattern: /핸드/gu, expected: '손패' },
    { pattern: /(?:^|[\s(])패(?:를|에|에서|의|가|와|로| 중)/gu, expected: '손패' },
    { pattern: /\b(?:Dark|Flame|Electric|Wind)\b/gu, expected: '현지화된 속성명' },
    { pattern: /암(?:\s*속성|으로)|풍(?:\s*속성|으로)/gu, expected: '어둠／바람' },
    { pattern: /영역 인챈트/gu, expected: '에리어 인챈트' },
    { pattern: /\bChronos\b/gu, expected: '크로노스' },
  ],
};

export function rulesTerminologyViolations(locale: RulesTerminologyLocale, value: string): string[] {
  return (NON_CANONICAL_PATTERNS[locale] ?? []).flatMap(({ pattern, expected }) => {
    pattern.lastIndex = 0;
    const matches = [...value.matchAll(pattern)].map((match) => match[0].trim()).filter(Boolean);
    return [...new Set(matches)].map((match) => `${match} -> ${expected}`);
  });
}

export function assertCanonicalRulesTerminology(locale: RulesTerminologyLocale, value: string, label: string): void {
  const violations = rulesTerminologyViolations(locale, value);
  if (violations.length > 0) {
    throw new Error(`Non-canonical rules terminology in ${label}: ${violations.join(', ')}`);
  }
}
